version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgirs_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env